server:
  port: 8888

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/mdsagir/config-repo
          default-label: master
          timeout: 5
          clone-on-start: true
          force-pull: true
